trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - README.md

pool:
  vmImage: 'windows-latest'

variables:
  - group: 'Build Variables'
  - name: solution
    value: '**/*.sln'
  - name:  buildPlatform
    value: 'Any CPU'
  - name: buildConfiguration
    value: 'Release'

steps:

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/*.sln'
    feedsToUse: 'select'
    vstsFeed: $(VstsFeed)

- task: DotNetCoreCLI@2
  displayName: 'dotnet build $(buildConfiguration)'
  inputs:
    command: 'build'
    projects: '**/*.sln'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'dotnet publish $(buildConfiguration)'
  inputs:
    command: 'publish'
    projects: '**/*.csproj'
    publishWebProjects: false
    arguments: '--configuration $(BuildConfiguration) --no-build --output $(Build.ArtifactStagingDirectory)/Deploy'
    modifyOutputPath: true
    zipAfterPublish: true

- publish: '$(Build.ArtifactStagingDirectory)/Deploy'
  artifact: 'Lunitor.AutomaticShutdown'

